# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/house_pricing_nbdev',
                'doc_host': 'https://IshmaelAsab.github.io',
                'git_url': 'https://github.com/IshmaelAsab/house_pricing_nbdev',
                'lib_path': 'house_pricing_nbdev'},
  'syms': {'house_pricing_nbdev.core': {'house_pricing_nbdev.core.foo': ('core.html#foo', 'house_pricing_nbdev/core.py')}}}
